name: Python CI and README Sync

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Python 환경 설정
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      # 의존성 설치
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      # pytest를 사용한 테스트 실행
      - name: Run tests with pytest
        run: |
          pytest tests --verbose --junitxml=test-results.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      # 테스트 결과 업로드
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.xml

  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Python 환경 설정
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # 의존성 설치
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      # `make readme` 명령어로 README.md 파일 생성
      - name: Generate README.md
        run: |
          make readme  # Makefile에서 정의한 readme 명령어 실행

      # 변경된 README.md 파일을 커밋하고 푸시
      - name: Commit updated README.md
        run: |
          git config --global user.name "Your GitHub Username"
          git config --global user.email "your-email@example.com"
          git add README.md
          git commit -m "Update README.md automatically"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
